import Head from 'next/head'
import { Box } from '@mui/material'
import { useEffect, useState } from 'react'
import ReactPlayer from 'react-player/youtube'
export default function Home() {
  // const [src,setSrc]=useState('https://www.youtube.com/embed/GNWLILeztaI?controls=0&autoplay=1&mute=0')
  const radiosStations=[{
    name:'Anime Vibe',
    video:'https://www.youtube.com/embed/6Y2aEZ-BBGQ?autoplay=1&mute=1&start=0',
    audio:'https://www.youtube.com/embed/6Y2aEZ-BBGQ?autoplay=1&mute=1&start=0',
  },{
    name:'Anime Vibe 2',
    video:'https://www.youtube.com/embed/CUZgFxseyGo?autoplay=1&mute=1&start=0',
    audio:'https://www.youtube.com/embed/CUZgFxseyGo?autoplay=1&mute=1&start=0'
  }]
  const [muted, setMuted] = useState(true)
  const [playing, setPlaying] = useState(true)
  const [videoSrc,setVideoSrc] = useState('')
  const [audioSrc,setAudioSrc] = useState('')
  useEffect(() => {
    const evt = new MouseEvent('click', {
      view: window,
      bubbles: true,
      cancelable: true,
      clientX: 20,
    })
    // document.getElementById('but').dispatchEvent(evt)
   
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box
        component='main'
        sx={{
          position: 'fixed',
          width: '100vw',
          height: '100vh',
        }}
      >
        <Box className='video-container' sx={{ border: '5px solid green' }}
          onClick={(e)=>{
            e.preventDefault()
            e.stopPropagation()
          }}
        >
          <ReactPlayer
            style={{ opacity: '0' }}
            playing={playing}
            muted={muted}
            url={audioSrc}
          />
          <ReactPlayer
            width='unset'
            height='unset'
            className='video-iframe'
            loop={true}
            playing={playing}
            muted={true}
            url={videoSrc}
          />
        </Box>
        <Box
          className='video-controller'
          sx={{
            position: 'absolute',
            width: '100%',
            bottom: '50px',
            display: 'flex',
            justifyContent: 'center',
          }}
        >
          <button
            id='but'
            style={{ zIndex: '100', padding: '10px' }}
            onClick={(e) => {
              console.log('hello')
              setMuted(state=>!state)
              setPlaying((state) => !state)
            }}
          >
            NEXT
          </button>
          {radiosStations.map(station=>(
            <button onClick={()=>{
              setVideoSrc(station.video)
              setAudioSrc(station.audio)
              setMuted(false)
            }}>RADIO</button>
          ))}
        </Box>
      </Box>
    </>
  )
}
